### ISSUE TITLE
Returns undefined on server

### ISSUE THREAD

**Issue by avalanche1** [jboulhous/dev#1]
Can we add this variable to server pls?

**Comment by jboulhous** [comment]
Hello, 
Sorry, did not catch the issue, and received no email.
do you still need this feature!

Meteor has it now in [core](https://github.com/meteor/meteor/blob/devel/packages/meteor/server_environment.js#L10-L17)

**Comment by avalanche1** [comment]
Ah, yes, they do. Well, thx for that nifty feature - it had it's uses)
